[package]
name = "trading_sessions"
version = "0.1.0"
edition = "2021"
authors = ["Floris floris@xylex.ai & Hadi hadi@xylex.ai"]
description = "A lightweight Sessions library in Rust"
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polars = {version = "0.37", features = ["lazy"] }
